# Generated by Django 3.0.7 on 2020-06-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
