# Generated by Django 3.0.7 on 2020-06-08 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0006_auto_20200608_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='temperatureReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotapp.device')),
            ],
        ),
        migrations.CreateModel(
            name='humidityReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotapp.device')),
            ],
        ),
    ]
